apiVersion: v1
kind: Pod
metadata:
  name: traefik
spec:
  containers:
  - name: traefik
    image: docker.io/traefik:latest
    args:
      - "--accesslog=true"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.ws"
